"""Shared Hot-Box plant constants and mirror pointing geometry."""

from .aiming import (
    CenterRay,
    MirrorGridSpec,
    MountAngles,
    bisector_normal_at_mount,
    evaluate_center_ray,
    horizontal_stow_angles,
    pivot_facet_center_world,
    refine_tracking_for_mount_offset,
    solve_bisector_tracking,
    solve_bisector_tracking_for_grid,
    solve_tracking,
    solve_tracking_for_grid,
    sun_elevation_deg,
    sun_is_above_horizon,
)
from .load import default_system_yaml_path, load_system_constants
from .mount import (
    MountJointLimits,
    apply_mount_joint_limits,
    dual_mount_angles,
    facet_normal_world,
    heading_and_tilt_from_normal,
    mount_az_el_align_body_normal_to_world,
    mount_rotation_matrix,
    normalize_mount_az_el,
    oven_facing_azimuth_deg,
    pivot_facet_normal_body,
    relative_azimuth_deg,
    within_mount_joint_limits,
)
from .site_time import (
    SitePose,
    as_site_local,
    ensure_utc,
    format_site_local,
    hours_since_site_midnight,
    local_times_sunrise_to_sunset,
    site_local_date,
    site_local_datetime,
    utc_now,
)
from .system import (
    AbsorberConstants,
    ControlConstants,
    FleetConstants,
    MirrorConstants,
    MountDesign,
    SiteConstants,
    SystemConstants,
)
from .vectors import bisector_normal, normalize, reflect_ray

__all__ = [
    "AbsorberConstants",
    "CenterRay",
    "ControlConstants",
    "FleetConstants",
    "MirrorConstants",
    "MirrorGridSpec",
    "MountAngles",
    "MountDesign",
    "MountJointLimits",
    "SiteConstants",
    "SitePose",
    "SystemConstants",
    "apply_mount_joint_limits",
    "as_site_local",
    "bisector_normal",
    "bisector_normal_at_mount",
    "default_system_yaml_path",
    "dual_mount_angles",
    "ensure_utc",
    "evaluate_center_ray",
    "facet_normal_world",
    "format_site_local",
    "heading_and_tilt_from_normal",
    "horizontal_stow_angles",
    "hours_since_site_midnight",
    "load_system_constants",
    "local_times_sunrise_to_sunset",
    "mount_az_el_align_body_normal_to_world",
    "mount_rotation_matrix",
    "normalize",
    "normalize_mount_az_el",
    "oven_facing_azimuth_deg",
    "pivot_facet_center_world",
    "pivot_facet_normal_body",
    "refine_tracking_for_mount_offset",
    "reflect_ray",
    "relative_azimuth_deg",
    "site_local_date",
    "site_local_datetime",
    "solve_bisector_tracking",
    "solve_bisector_tracking_for_grid",
    "solve_tracking",
    "solve_tracking_for_grid",
    "sun_elevation_deg",
    "sun_is_above_horizon",
    "utc_now",
    "within_mount_joint_limits",
]
