[platformio]
default_envs = nano_esp32

[env:nano_esp32]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
monitor_speed = 115200
lib_deps =
    madhephaestus/ESP32Encoder
    br3ttb/PID
    sandeepmistry/CAN
build_flags =
    -D HOTBOX_NODE_ID=0
